"""Reproducible OCPP native shadow validation report from captured replay fixtures.

Replays each fixture through the read-only OCPP import/export shadow ledgers,
the aligned-window reconciliation and the native session lifecycle
(``custom_components/bsv_settlement/ocpp_replay.py``), then writes a Markdown
summary: sessions, directional totals, divergence against the Sigen reference
counters, and quality flags.

Deterministic: the output depends only on the fixture files and the code. It
contains no wall-clock time, host or git data, so regenerating it from the same
inputs gives a byte-identical file. Offline only: no HA, wallet or charger.

Usage::

    python scripts/ocpp_shadow_report.py tests/fixtures/ocpp_lifecycle/live_*.json \
        --title "..." --output docs/qa/ocpp-shadow-report-2026-10-05.md
"""
import argparse
from collections import Counter
from decimal import Decimal
import hashlib
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from custom_components.bsv_settlement.ocpp_replay import load, replay  # noqa: E402

DEFAULT_TITLE = "OCPP native shadow validation report"


def _dec(value):
    return Decimal(value) if value is not None else None


def _kwh(value):
    return "—" if value is None else f"{Decimal(value):.3f}"


def _pct(value):
    return "—" if value is None else f"{Decimal(value):+.2f} %"


def _time(value):
    return "open" if value is None else value[:19].replace("T", " ")


def _short(value):
    return "open" if value is None else value[11:19]


def _rel(path):
    try:
        return Path(path).resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return Path(path).name


def run(paths):
    results = []
    for path in paths:
        fixture = load(path)
        digest = hashlib.sha256(Path(path).read_bytes()).hexdigest()
        results.append((path, digest, fixture, replay(fixture)))
    return results


def _direction_cell(row):
    return (f"{_kwh(row['observed_kwh'])} / {_kwh(row.get('reference_observed_kwh'))} "
            f"({_pct(row.get('divergence_pct'))}) {row.get('comparison', '—')}")


def render(results, title=DEFAULT_TITLE):
    lines = [f"# {title}", ""]
    lines += [
        "Generated by `scripts/ocpp_shadow_report.py` from the replay fixtures listed",
        "below. Regenerating from the same fixtures and code gives this file byte for",
        "byte. See [OCPP lifecycle replay](../ocpp-lifecycle-replay.md) for the method.",
        "",
        "**Safety boundary.** Offline replay of read-only captures. The OCPP recorder",
        "remains shadow-only: `billing_eligible` is false on every session and span,",
        "the settlement owner stays `legacy_sigen`, and no charger, wallet or Home",
        "Assistant action was taken. Vehicle attribution is never automatic.",
        "",
        "## Inputs", "",
        "| Fixture | Evidence | Window | Events | SHA-256 (first 16) |",
        "| --- | --- | --- | ---: | --- |",
    ]
    for path, digest, fixture, _ in results:
        window = fixture.get("window") or {}
        lines.append(f"| `{_rel(path)}` | {fixture['evidence']} | "
                     f"{_time(window.get('start'))} → {_time(window.get('end'))} | "
                     f"{len(fixture['events'])} | `{digest[:16]}` |")
    tolerances = results[0][3]["tolerances"] if results else {}
    lines += ["", "Tolerances (documented defaults, "
              "[recorder readiness](../recorder-readiness.md#tolerances)): import "
              f"{tolerances.get('import_pct')} % (floor {tolerances.get('import_floor_kwh')} kWh), "
              f"export {tolerances.get('export_pct')} % (floor "
              f"{tolerances.get('export_floor_kwh')} kWh), minimum energy "
              f"{tolerances.get('min_energy_kwh')} kWh.", ""]

    sessions = [(fixture, s) for _, _, fixture, r in results for s in r["sessions"]]
    restarts = sum(len(r["ha_restarts"]) for *_, r in results)
    spans = {d: sum(len(r[f"{d}_spans"]) for *_, r in results) for d in ("import", "export")}
    overlaps = sum(len(r["overlapping_sessions"]) for *_, r in results)
    lines += ["## Summary", "",
              f"- Fixtures: {len(results)}; native sessions: {len(sessions)}; HA restarts "
              f"replayed: {restarts}; overlapping sessions: {overlaps}.",
              f"- Closed shadow spans: import {spans['import']}, export {spans['export']}.",
              "- Billing eligible sessions: "
              f"{sum(1 for _, s in sessions if s['billing_eligible'])}; "
              "automatic vehicle attributions: "
              f"{sum(1 for _, s in sessions if s['vehicle_attribution'] != 'unresolved')}."]
    for direction in ("import", "export"):
        rows = [s[direction] for _, s in sessions]
        compared = [r for r in rows if r.get("reference_observed_kwh") is not None
                    and r["observed_kwh"] is not None]
        observed = sum((_dec(r["observed_kwh"]) for r in compared), Decimal(0))
        reference = sum((_dec(r["reference_observed_kwh"]) for r in compared), Decimal(0))
        counts = Counter(r.get("comparison", "unresolved") for r in rows)
        divergence = (f"{(observed - reference) / reference * 100:+.2f} %" if reference
                      else "—")
        lines.append(
            f"- {direction.capitalize()}: observed {_kwh(observed)} kWh against reference "
            f"{_kwh(reference)} kWh over the same span windows ({divergence}); comparisons "
            + ", ".join(f"{k} {v}" for k, v in sorted(counts.items())) + ".")
    lines.append("")

    lines += ["## Sessions", "",
              "Session identity is (charger, connector, OCPP transactionId, start). Energy "
              "cells read *observed / reference over the same span windows (divergence) "
              "comparison*; `—` means not observed, never zero.", "",
              "| Fixture | Transaction | Start → end | End | Restarts | Import kWh | "
              "Export kWh (estimated) | Export grades | Reference session kWh (imp / exp) |",
              "| --- | --- | --- | --- | ---: | --- | --- | --- | --- |"]
    for fixture, s in sessions:
        lines.append(
            f"| {fixture['fixture']} | {s['transaction_id']} | {_time(s['started_at'])} → "
            f"{_short(s['ended_at'])} | {s['end_reason'] or 'open'} | {len(s['ha_restarts'])} | "
            f"{_direction_cell(s['import'])} | {_direction_cell(s['export'])} | "
            f"{', '.join(s['export'].get('grades') or []) or '—'} | "
            f"{_kwh(s['import'].get('reference_session_kwh'))} / "
            f"{_kwh(s['export'].get('reference_session_kwh'))} |")
    lines.append("")

    lines += ["## Quality flags by session", "",
              "| Fixture | Transaction | Flags |", "| --- | --- | --- |"]
    for fixture, s in sessions:
        lines.append(f"| {fixture['fixture']} | {s['transaction_id']} | "
                     f"{', '.join(f'`{f}`' for f in s['quality_flags']) or '—'} |")
    counts = Counter(flag for _, s in sessions for flag in s["quality_flags"])
    lines += ["", "| Flag | Sessions |", "| --- | ---: |"]
    lines += [f"| `{flag}` | {n} |" for flag, n in sorted(counts.items())]
    lines.append("")

    lines += ["## Attribution evidence", "",
              "idTag references are one-way hashes of the sanitised per-fixture placeholders, "
              "so they are comparable only within one fixture. They are shown to demonstrate "
              "that the idTag does not track the vehicle; they are not used for identity, "
              "ownership or attribution. SoC is the first and last charger SoC sample after "
              "the session start; continuity is evidence for an operator, not attribution.", "",
              "| Fixture | Transaction | idTag refs | idTag changes in tx | SoC first → last | "
              "SoC vs previous session | Vehicle attribution |",
              "| --- | --- | --- | ---: | --- | --- | --- |"]
    for fixture, s in sessions:
        meta, evidence = s["untrusted_metadata"], s["vehicle_evidence"] or {}
        soc = (f"{(s['soc_first'] or {}).get('pct', '—')} → {(s['soc_last'] or {}).get('pct', '—')}")
        change = ("—" if evidence.get("delta_pct") is None else
                  f"{evidence['assessment']} ({Decimal(evidence['delta_pct']):+} pts)")
        lines.append(f"| {fixture['fixture']} | {s['transaction_id']} | "
                     f"{', '.join(f'`{r}`' for r in meta['id_tag_refs']) or '—'} | "
                     f"{meta['id_tag_changes']} | {soc} | {change} | {s['vehicle_attribution']} |")
    lines.append("")

    lines += ["## Reading this report", "",
              "- Observed energy is the sum of conservative shadow spans. Energy before a "
              "fresh baseline, across an HA restart, a meter gap or a stale flat register is "
              "excluded and appears as `*_reference_energy_outside_observed_spans`.",
              "- The import register does not change while the vehicle discharges, so its "
              "HA state goes stale and the import span closes (`import_invalid_or_stale_meter`). "
              "That is expected, not a fault.",
              "- Export is the fork's derived estimate (`export_estimated`), graded by its "
              "bound spread; it stays non-billable whatever the divergence.",
              "- HA arrival times align both sides; the reference counters have 10 Wh "
              "resolution and roughly 5 s cadence.", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("fixtures", nargs="+")
    parser.add_argument("--title", default=DEFAULT_TITLE)
    parser.add_argument("--output")
    args = parser.parse_args()
    text = render(run(sorted(args.fixtures)), args.title)
    if args.output:
        Path(args.output).write_text(text)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
